default: &default
  adapter: <%= ENV['RAILS_DB_ADAPTER'] || 'sqlite3' %>
  pool: 5
  timeout: 5000
  encoding: utf8
<% %w(host port username password socket).each do |opt| %>
  <% val = ENV["RAILS_DB_#{opt.upcase}"] %>
  <%= "#{opt}: #{val}" if val.present? %>
<% end %>

development:
  <<: *default
  database: <%= ENV['RAILS_DB_NAME'] || "#{Rails.root}/db/development.sqlite3" %>

test:
  <<: *default
  database: <%= ENV['RAILS_TEST_DB_NAME'] || ENV['RAILS_DB_NAME'] || "#{Rails.root}/db/test.sqlite3" %>

production:
  <<: *default
  database: <%= ENV['RAILS_DB_NAME'] || "#{Rails.root}/db/production.sqlite3" %>
