# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: facbf20ec48b8434d877940bd2fd4be8eb07b9e1d33830a94ac8ba08bed6ea131c28c029d4695482d54324998d83fcd88b986167f7135b9c764d95a022506a2e

test:
  secret_key_base: bf5dc1c5874d012633418f99700a00a97db44fe3c1d5f77afdf3e58b1bb2e3ed710597626fee80bec5db431e29f620ad70da75702bf9280efc10d2d4b948c4dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
